import CoreGraphics
import XCTest
@testable import LanMessenger

/// The HID usage to macOS virtual key table, and its inverse.
///
/// A table like this fails in the worst possible way: one wrong entry means one
/// key types the wrong character, on someone else's machine, and nobody notices
/// until they try that key. It cannot be verified by using it — that would mean
/// pressing every key on a remote host — so the properties that must hold are
/// asserted directly.
///
/// The Windows twin of this suite checks the same shape against PS/2 scan codes.
final class HidKeyMapTests: XCTestCase {

    func testEveryLetterAndDigitIsMapped() {
        for usage in UInt16(0x04)...UInt16(0x27) {
            XCTAssertNotNil(HidKeyMap.virtualKey(for: usage),
                            String(format: "HID 0x%02X has no virtual key", usage))
        }
    }

    func testNoTwoUsagesShareAVirtualKey() {
        // The single most likely defect: a copied line left pointing at the
        // previous key's code. Two usages with the same virtual key are
        // indistinguishable to macOS, so one of them types the other — and the
        // inverse table silently loses one of them too.
        var seen: [CGKeyCode: UInt16] = [:]
        for usage in UInt16(0x00)...UInt16(0xFF) {
            guard let code = HidKeyMap.virtualKey(for: usage) else { continue }
            XCTAssertNil(seen[code],
                         String(format: "HID 0x%02X and 0x%02X both map to key 0x%02X",
                                usage, seen[code] ?? 0, code))
            seen[code] = usage
        }
    }

    func testLettersMapToPositionsNotAlphabeticalOrder() {
        // HID orders letters A-Z; the keyboard does not. A is 0x00 (left of S)
        // and Q is 0x0C (top-left). If these come out sequential, the table was
        // generated by counting rather than by position and every letter is
        // wrong.
        XCTAssertEqual(HidKeyMap.virtualKey(for: 0x04), 0x00)   // A
        XCTAssertEqual(HidKeyMap.virtualKey(for: 0x14), 0x0C)   // Q
        XCTAssertEqual(HidKeyMap.virtualKey(for: 0x1D), 0x06)   // Z
        XCTAssertEqual(HidKeyMap.virtualKey(for: 0x1C), 0x10)   // Y
    }

    func testFunctionKeysAreNotASequence() {
        // Unlike the Windows scan codes, these really are scattered — F1 to F4
        // are 0x7A, 0x78, 0x63, 0x76, which descends then jumps. A table that
        // derived them would be wrong from F2 onward.
        XCTAssertEqual(HidKeyMap.virtualKey(for: 0x3A), 0x7A)   // F1
        XCTAssertEqual(HidKeyMap.virtualKey(for: 0x3B), 0x78)   // F2
        XCTAssertEqual(HidKeyMap.virtualKey(for: 0x3C), 0x63)   // F3
        XCTAssertEqual(HidKeyMap.virtualKey(for: 0x45), 0x6F)   // F12
    }

    func testEveryModifierIsMappableAndDistinct() {
        // `releaseEverything` walks this list at teardown. An entry with no key
        // code would be a modifier that can be pressed and never lifted.
        var codes: Set<CGKeyCode> = []
        for usage in HidKeyMap.modifierUsages {
            guard let code = HidKeyMap.virtualKey(for: usage) else {
                return XCTFail(String(format: "modifier HID 0x%02X cannot be released", usage))
            }
            XCTAssertTrue(codes.insert(code).inserted,
                          String(format: "modifier HID 0x%02X reuses a key code", usage))
        }
    }

    func testAnUnknownUsageIsNilRatherThanZero() {
        // Zero is a real key code (it is `A`), so returning it for "unknown"
        // would type a letter for every unrecognised usage.
        XCTAssertNil(HidKeyMap.virtualKey(for: 0xFFFF))
        XCTAssertNil(HidKeyMap.virtualKey(for: 0x00))
    }

    func testModifierFlagsMapToCoreGraphicsFlags() {
        XCTAssertTrue(HidKeyMap.flags(for: [.meta]).contains(.maskCommand))
        XCTAssertTrue(HidKeyMap.flags(for: [.option]).contains(.maskAlternate))
        XCTAssertTrue(HidKeyMap.flags(for: [.shift, .control])
                        .isSuperset(of: [.maskShift, .maskControl]))
        XCTAssertEqual(HidKeyMap.flags(for: []), [])
    }

    // MARK: - The inverse

    func testTheInverseTableAgreesWithTheForwardOne() {
        // The capture side inverts this table rather than repeating it, so the
        // two cannot drift. This asserts the inversion is total: every usage the
        // host can press is one the viewer can send.
        for usage in UInt16(0x00)...UInt16(0xFF) {
            guard let code = HidKeyMap.virtualKey(for: usage) else { continue }
            XCTAssertEqual(RemoteHidUsage.usage(forVirtualKey: UInt16(code)), usage,
                           String(format: "HID 0x%02X did not survive the round trip", usage))
        }
    }

    func testAnUnmappedVirtualKeyProducesNoUsage() {
        // 0xFF is not a key. Returning a usage for it would send a keystroke
        // nobody pressed.
        XCTAssertNil(RemoteHidUsage.usage(forVirtualKey: 0xFF))
    }
}
