import XCTest
@testable import LanMessenger

/// The input sub-channel's wire records.
///
/// The byte expectations here are hand-computed from PROTOCOL.md rather than
/// captured from this implementation. A vector generated by the code it tests
/// only proves the code agrees with itself, and the whole point of these records
/// is that a Mac and a PC agree — `remote_input_vector.json` carries the same
/// bytes into the Windows suite.
final class RemoteInputRecordTests: XCTestCase {

    // MARK: - Wire format

    func testPointerMoveMatchesTheSpecifiedBytes() {
        let data = RemoteInputCodec.encode(.pointerMove(x: 0.25, y: 0.75))
        XCTAssertEqual(hex(data), "013e8000003f400000")
    }

    func testPointerButtonMatchesTheSpecifiedBytes() {
        let data = RemoteInputCodec.encode(
            .pointerButton(button: .left, down: true, x: 0.5, y: 0.5))
        XCTAssertEqual(hex(data), "0200013f0000003f000000")
    }

    func testPointerScrollMatchesTheSpecifiedBytes() {
        let data = RemoteInputCodec.encode(
            .pointerScroll(dx: -1.0, dy: 2.0, x: 0.1, y: 0.9))
        XCTAssertEqual(hex(data), "03bf800000400000003dcccccd3f666666")
    }

    func testKeyMatchesTheSpecifiedBytes() {
        let data = RemoteInputCodec.encode(
            .key(usage: 0x04, down: true, repeating: false, modifiers: [.shift, .meta]))
        XCTAssertEqual(hex(data), "04000401000009")
    }

    func testTextMatchesTheSpecifiedBytes() {
        XCTAssertEqual(hex(RemoteInputCodec.encode(.text("hi"))), "0500026869")
    }

    func testEveryRecordRoundTrips() {
        let records: [RemoteInputRecord] = [
            .pointerMove(x: 0, y: 1),
            .pointerButton(button: .middle, down: false, x: 0.33, y: 0.66),
            .pointerScroll(dx: 3, dy: -4, x: 0.5, y: 0.5),
            .key(usage: 0x2C, down: false, repeating: true, modifiers: [.control]),
            .text("héllo 👋"),
        ]
        for record in records {
            XCTAssertEqual(RemoteInputCodec.decode(RemoteInputCodec.encode(record)), [record],
                           "\(record) did not survive a round trip")
        }
    }

    func testSeveralRecordsTravelInOnePayload() {
        // A burst of pointer moves must not cost a frame each.
        let burst: [RemoteInputRecord] = [
            .pointerMove(x: 0.25, y: 0.75),
            .pointerButton(button: .left, down: true, x: 0.5, y: 0.5),
        ]
        let data = RemoteInputCodec.encode(burst)
        XCTAssertEqual(hex(data), "013e8000003f4000000200013f0000003f000000")
        XCTAssertEqual(RemoteInputCodec.decode(data), burst)
    }

    // MARK: - Hostile input

    func testATruncatedRecordIsRejectedRatherThanGuessed() {
        // Every byte here came from a peer. A short record means the stream
        // position is no longer trustworthy, and injecting the prefix of a
        // corrupted burst is worse than injecting nothing.
        let full = RemoteInputCodec.encode(.pointerMove(x: 0.25, y: 0.75))
        for cut in 1..<full.count {
            XCTAssertNil(RemoteInputCodec.decode(full.prefix(cut)),
                         "a \(cut)-byte pointer_move should not decode")
        }
    }

    func testAnUnknownRecordTypeIsRejected() {
        // Not skipped: without a length this build cannot know where the next
        // record starts, so continuing would be guessing.
        XCTAssertNil(RemoteInputCodec.decode(Data([0x77, 0x00, 0x00])))
    }

    func testAReservedButtonIsSkippedButTheStreamContinues() {
        // Unlike an unknown type, this record's length IS known — so the stream
        // stays trustworthy and only the one record is dropped.
        var reserved = Data([0x02, 0x09, 0x01])       // button 9, reserved
        reserved.append(contentsOf: [0x3f, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x00, 0x00])
        let payload = reserved + RemoteInputCodec.encode(.key(usage: 0x04, down: true,
                                                              repeating: false, modifiers: []))
        let decoded = RemoteInputCodec.decode(payload)
        XCTAssertEqual(decoded, [.key(usage: 0x04, down: true, repeating: false, modifiers: [])])
    }

    func testTextLongerThanTheCapIsRefusedOnTheWayIn() {
        // The encoder truncates; the decoder refuses. A peer that claims more
        // than the cap is not a peer with a long string, it is a peer trying to
        // make us allocate.
        var data = Data([0x05])
        data.append(contentsOf: [0xFF, 0xFF])          // claims 65535 bytes
        data.append(contentsOf: Array(repeating: 0x41, count: 16))
        XCTAssertNil(RemoteInputCodec.decode(data))
    }

    func testInvalidUTF8IsAMalformedRecordNotAnEmptyString() {
        // Silently injecting nothing would look like a dropped keystroke rather
        // than a broken peer.
        var data = Data([0x05, 0x00, 0x02])
        data.append(contentsOf: [0xC3, 0x28])          // invalid continuation
        XCTAssertNil(RemoteInputCodec.decode(data))
    }

    func testTextIsTruncatedOnACharacterBoundary() {
        // Half a UTF-8 sequence is not a shorter string, it is an invalid one.
        let long = String(repeating: "👋", count: 600)   // 4 bytes each, well over the cap
        let data = RemoteInputCodec.encode(.text(long))
        guard case .text(let decoded)? = RemoteInputCodec.decode(data)?.first else {
            return XCTFail("a truncated text record should still decode")
        }
        XCTAssertLessThanOrEqual(decoded.utf8.count, RemoteInputRecord.maxTextBytes)
        XCTAssertTrue(decoded.allSatisfy { $0 == "👋" }, "truncation split a character")
    }

    func testUnknownModifierBitsAreIgnoredRatherThanRejected() {
        // A newer peer may set one, and refusing the record would turn a
        // forward-compatible addition into a dead keyboard.
        var data = Data([0x04, 0x00, 0x04, 0x01, 0x00])
        data.append(contentsOf: [0xFF, 0xFF])          // every bit set
        guard case .key(_, _, _, let modifiers)? = RemoteInputCodec.decode(data)?.first else {
            return XCTFail("a key with unknown modifier bits should still decode")
        }
        XCTAssertEqual(modifiers, .known)
    }

    // MARK: - Helpers

    private func hex(_ data: Data) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }
}
