// GENERATED by scripts/design/gen_tokens.py from design/liquid-glass/tokens.json. Do not edit.

using Windows.UI;

namespace LanMessenger.UI;

/// <summary>
/// The design tokens for code-behind. XAML reads the same values from
/// Styles/GlassTokens.xaml as Token*Brush / Token*Color resources.
/// </summary>
public static class GlassTokens
{
    /// <summary>The value for the current theme, as Theme.Initialize last set it.</summary>
    public static Color Pick(Color light, Color dark) => Theme.IsDark ? dark : light;

    public static readonly Color BrandLight = Color.FromArgb(0xFF, 0x25, 0xD3, 0x66);
    public static readonly Color BrandDark = Color.FromArgb(0xFF, 0x25, 0xD3, 0x66);
    public static readonly Color BrandHoverLight = Color.FromArgb(0xFF, 0x1E, 0xBE, 0x5D);
    public static readonly Color BrandHoverDark = Color.FromArgb(0xFF, 0x1E, 0xBE, 0x5D);
    public static readonly Color BrandPressedLight = Color.FromArgb(0xFF, 0x1A, 0xAD, 0x54);
    public static readonly Color BrandPressedDark = Color.FromArgb(0xFF, 0x1A, 0xAD, 0x54);
    public static readonly Color OnBrandLight = Color.FromArgb(0xFF, 0x0B, 0x14, 0x1A);
    public static readonly Color OnBrandDark = Color.FromArgb(0xFF, 0x0B, 0x14, 0x1A);
    public static readonly Color AccentInkLight = Color.FromArgb(0xFF, 0x00, 0x6B, 0x57);
    public static readonly Color AccentInkDark = Color.FromArgb(0xFF, 0x25, 0xD3, 0x66);
    public static readonly Color AccentInkOutLight = Color.FromArgb(0xFF, 0x00, 0x6B, 0x57);
    public static readonly Color AccentInkOutDark = Color.FromArgb(0xFF, 0x8A, 0xF0, 0xB5);
    public static readonly Color AccentWashLight = Color.FromArgb(0x24, 0x25, 0xD3, 0x66);
    public static readonly Color AccentWashDark = Color.FromArgb(0x29, 0x25, 0xD3, 0x66);
    public static readonly Color FocusRingLight = Color.FromArgb(0xFF, 0x00, 0x6B, 0x57);
    public static readonly Color FocusRingDark = Color.FromArgb(0xFF, 0x25, 0xD3, 0x66);
    public static readonly Color WallpaperLight = Color.FromArgb(0xFF, 0xE5, 0xDD, 0xD5);
    public static readonly Color WallpaperDark = Color.FromArgb(0xFF, 0x0D, 0x14, 0x18);
    public static readonly Color WallpaperGlowLight = Color.FromArgb(0x29, 0x25, 0xD3, 0x66);
    public static readonly Color WallpaperGlowDark = Color.FromArgb(0x24, 0x25, 0xD3, 0x66);
    public static readonly Color WallpaperGlowAltLight = Color.FromArgb(0x1F, 0x00, 0x80, 0x69);
    public static readonly Color WallpaperGlowAltDark = Color.FromArgb(0x1F, 0x00, 0xA8, 0x84);
    public static readonly Color SidebarGroundLight = Color.FromArgb(0xFF, 0xF0, 0xF2, 0xF5);
    public static readonly Color SidebarGroundDark = Color.FromArgb(0xFF, 0x11, 0x1B, 0x21);
    public static readonly Color GlassClearLight = Color.FromArgb(0x4D, 0xFF, 0xFF, 0xFF);
    public static readonly Color GlassClearDark = Color.FromArgb(0x4D, 0x11, 0x1B, 0x21);
    public static readonly Color GlassRegularLight = Color.FromArgb(0x9E, 0xF8, 0xFA, 0xFB);
    public static readonly Color GlassRegularDark = Color.FromArgb(0x9E, 0x11, 0x1B, 0x21);
    public static readonly Color GlassThickLight = Color.FromArgb(0xD1, 0xFA, 0xFB, 0xFC);
    public static readonly Color GlassThickDark = Color.FromArgb(0xD6, 0x16, 0x1F, 0x25);
    public static readonly Color GlassRegularFallbackLight = Color.FromArgb(0xFF, 0xF0, 0xF2, 0xF5);
    public static readonly Color GlassRegularFallbackDark = Color.FromArgb(0xFF, 0x11, 0x1B, 0x21);
    public static readonly Color GlassThickFallbackLight = Color.FromArgb(0xFF, 0xFA, 0xFB, 0xFC);
    public static readonly Color GlassThickFallbackDark = Color.FromArgb(0xFF, 0x16, 0x1F, 0x25);
    public static readonly Color GlassRimLight = Color.FromArgb(0xE6, 0xFF, 0xFF, 0xFF);
    public static readonly Color GlassRimDark = Color.FromArgb(0x29, 0xFF, 0xFF, 0xFF);
    public static readonly Color GlassSheenLight = Color.FromArgb(0x73, 0xFF, 0xFF, 0xFF);
    public static readonly Color GlassSheenDark = Color.FromArgb(0x0F, 0xFF, 0xFF, 0xFF);
    public static readonly Color GlassEdgeLight = Color.FromArgb(0x1A, 0x0B, 0x14, 0x1A);
    public static readonly Color GlassEdgeDark = Color.FromArgb(0x14, 0xFF, 0xFF, 0xFF);
    public static readonly Color GlassHoverLight = Color.FromArgb(0x2E, 0x80, 0x80, 0x80);
    public static readonly Color GlassHoverDark = Color.FromArgb(0x2E, 0x80, 0x80, 0x80);
    public static readonly Color GlassPressedLight = Color.FromArgb(0x45, 0x80, 0x80, 0x80);
    public static readonly Color GlassPressedDark = Color.FromArgb(0x45, 0x80, 0x80, 0x80);
    public static readonly Color InsetFillLight = Color.FromArgb(0x0D, 0x0B, 0x14, 0x1A);
    public static readonly Color InsetFillDark = Color.FromArgb(0x12, 0xFF, 0xFF, 0xFF);
    public static readonly Color ScrimLight = Color.FromArgb(0x8C, 0x0B, 0x14, 0x1A);
    public static readonly Color ScrimDark = Color.FromArgb(0x8C, 0x0B, 0x14, 0x1A);
    public static readonly Color DividerLight = Color.FromArgb(0x14, 0x0B, 0x14, 0x1A);
    public static readonly Color DividerDark = Color.FromArgb(0x12, 0xFF, 0xFF, 0xFF);
    public static readonly Color BubbleInLight = Color.FromArgb(0xDB, 0xFF, 0xFF, 0xFF);
    public static readonly Color BubbleInDark = Color.FromArgb(0xDB, 0x20, 0x2C, 0x33);
    public static readonly Color BubbleOutLight = Color.FromArgb(0xE6, 0xDC, 0xF8, 0xC6);
    public static readonly Color BubbleOutDark = Color.FromArgb(0xE0, 0x00, 0x5C, 0x4B);
    public static readonly Color BubbleInFallbackLight = Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF);
    public static readonly Color BubbleInFallbackDark = Color.FromArgb(0xFF, 0x20, 0x2C, 0x33);
    public static readonly Color BubbleOutFallbackLight = Color.FromArgb(0xFF, 0xDC, 0xF8, 0xC6);
    public static readonly Color BubbleOutFallbackDark = Color.FromArgb(0xFF, 0x00, 0x5C, 0x4B);
    public static readonly Color InkLight = Color.FromArgb(0xFF, 0x11, 0x1B, 0x21);
    public static readonly Color InkDark = Color.FromArgb(0xFF, 0xE9, 0xED, 0xEF);
    public static readonly Color InkSecondaryLight = Color.FromArgb(0xFF, 0x54, 0x65, 0x6F);
    public static readonly Color InkSecondaryDark = Color.FromArgb(0xFF, 0x86, 0x96, 0xA0);
    public static readonly Color MetaOutLight = Color.FromArgb(0xFF, 0x4F, 0x6B, 0x52);
    public static readonly Color MetaOutDark = Color.FromArgb(0xFF, 0xA9, 0xD1, 0xC6);
    public static readonly Color InkInverseLight = Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF);
    public static readonly Color InkInverseDark = Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF);
    public static readonly Color TickReadLight = Color.FromArgb(0xFF, 0x1A, 0x7F, 0xD4);
    public static readonly Color TickReadDark = Color.FromArgb(0xFF, 0x53, 0xBD, 0xEB);
    public static readonly Color PresenceOnlineLight = Color.FromArgb(0xFF, 0x1D, 0xA0, 0x5A);
    public static readonly Color PresenceOnlineDark = Color.FromArgb(0xFF, 0x25, 0xD3, 0x66);
    public static readonly Color PresenceOfflineLight = Color.FromArgb(0xFF, 0x86, 0x86, 0x8B);
    public static readonly Color PresenceOfflineDark = Color.FromArgb(0xFF, 0x8E, 0x8E, 0x93);
    public static readonly Color PresenceRingLight = Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF);
    public static readonly Color PresenceRingDark = Color.FromArgb(0xFF, 0x11, 0x1B, 0x21);
    public static readonly Color DangerLight = Color.FromArgb(0xFF, 0xD9, 0x30, 0x30);
    public static readonly Color DangerDark = Color.FromArgb(0xFF, 0xD9, 0x30, 0x30);
    public static readonly Color DangerInkLight = Color.FromArgb(0xFF, 0xC6, 0x28, 0x28);
    public static readonly Color DangerInkDark = Color.FromArgb(0xFF, 0xFF, 0x7B, 0x72);
    public static readonly Color DangerWashLight = Color.FromArgb(0x24, 0xD9, 0x30, 0x30);
    public static readonly Color DangerWashDark = Color.FromArgb(0x33, 0xD9, 0x30, 0x30);
    public static readonly Color WarningLight = Color.FromArgb(0xFF, 0xE6, 0x8C, 0x1A);
    public static readonly Color WarningDark = Color.FromArgb(0xFF, 0xE6, 0x8C, 0x1A);
    public static readonly Color OnWarningLight = Color.FromArgb(0xFF, 0x1F, 0x13, 0x00);
    public static readonly Color OnWarningDark = Color.FromArgb(0xFF, 0x1F, 0x13, 0x00);
    public static readonly Color WarningInkLight = Color.FromArgb(0xFF, 0x8A, 0x52, 0x00);
    public static readonly Color WarningInkDark = Color.FromArgb(0xFF, 0xF5, 0xB1, 0x4C);
    public static readonly Color WarningWashLight = Color.FromArgb(0x24, 0xE6, 0x8C, 0x1A);
    public static readonly Color WarningWashDark = Color.FromArgb(0x2E, 0xE6, 0x8C, 0x1A);
    public static readonly Color HudSurfaceLight = Color.FromArgb(0xFF, 0x1B, 0x1F, 0x23);
    public static readonly Color HudSurfaceDark = Color.FromArgb(0xFF, 0x1B, 0x1F, 0x23);
    public static readonly Color HudRimLight = Color.FromArgb(0x24, 0xFF, 0xFF, 0xFF);
    public static readonly Color HudRimDark = Color.FromArgb(0x24, 0xFF, 0xFF, 0xFF);
    public static readonly Color HudInkLight = Color.FromArgb(0xFF, 0xF2, 0xF4, 0xF5);
    public static readonly Color HudInkDark = Color.FromArgb(0xFF, 0xF2, 0xF4, 0xF5);
    public static readonly Color HudInkSecondaryLight = Color.FromArgb(0xFF, 0xA3, 0xAD, 0xB4);
    public static readonly Color HudInkSecondaryDark = Color.FromArgb(0xFF, 0xA3, 0xAD, 0xB4);
    public static readonly Color HudButtonLight = Color.FromArgb(0x1F, 0xFF, 0xFF, 0xFF);
    public static readonly Color HudButtonDark = Color.FromArgb(0x1F, 0xFF, 0xFF, 0xFF);
    public static readonly Color HudButtonHoverLight = Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF);
    public static readonly Color HudButtonHoverDark = Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF);
    public static readonly Color HudSignalViewLight = Color.FromArgb(0xFF, 0xF0, 0xA3, 0x3A);
    public static readonly Color HudSignalViewDark = Color.FromArgb(0xFF, 0xF0, 0xA3, 0x3A);
    public static readonly Color HudSignalControlLight = Color.FromArgb(0xFF, 0xFF, 0x61, 0x59);
    public static readonly Color HudSignalControlDark = Color.FromArgb(0xFF, 0xFF, 0x61, 0x59);
    public static readonly Color AvatarBlueLight = Color.FromArgb(0xFF, 0x2B, 0x6C, 0xD4);
    public static readonly Color AvatarBlueDark = Color.FromArgb(0xFF, 0x2B, 0x6C, 0xD4);
    public static readonly Color AvatarGreenLight = Color.FromArgb(0xFF, 0x1B, 0x7F, 0x45);
    public static readonly Color AvatarGreenDark = Color.FromArgb(0xFF, 0x1B, 0x7F, 0x45);
    public static readonly Color AvatarOrangeLight = Color.FromArgb(0xFF, 0xB5, 0x57, 0x00);
    public static readonly Color AvatarOrangeDark = Color.FromArgb(0xFF, 0xB5, 0x57, 0x00);
    public static readonly Color AvatarPurpleLight = Color.FromArgb(0xFF, 0x8E, 0x44, 0xC9);
    public static readonly Color AvatarPurpleDark = Color.FromArgb(0xFF, 0x8E, 0x44, 0xC9);
    public static readonly Color AvatarRedLight = Color.FromArgb(0xFF, 0xD0, 0x35, 0x2B);
    public static readonly Color AvatarRedDark = Color.FromArgb(0xFF, 0xD0, 0x35, 0x2B);
    public static readonly Color AvatarTealLight = Color.FromArgb(0xFF, 0x0B, 0x7F, 0x99);
    public static readonly Color AvatarTealDark = Color.FromArgb(0xFF, 0x0B, 0x7F, 0x99);
    public static readonly Color AvatarAmberLight = Color.FromArgb(0xFF, 0x9A, 0x65, 0x00);
    public static readonly Color AvatarAmberDark = Color.FromArgb(0xFF, 0x9A, 0x65, 0x00);
    public static readonly Color AvatarSlateLight = Color.FromArgb(0xFF, 0x5E, 0x67, 0x70);
    public static readonly Color AvatarSlateDark = Color.FromArgb(0xFF, 0x5E, 0x67, 0x70);

    /// <summary>Every colour token in both themes, in token order, for tests.</summary>
    public static readonly IReadOnlyList<(string Name, Color Light, Color Dark)> All =
    [
        ("brand", BrandLight, BrandDark),
        ("brand-hover", BrandHoverLight, BrandHoverDark),
        ("brand-pressed", BrandPressedLight, BrandPressedDark),
        ("on-brand", OnBrandLight, OnBrandDark),
        ("accent-ink", AccentInkLight, AccentInkDark),
        ("accent-ink-out", AccentInkOutLight, AccentInkOutDark),
        ("accent-wash", AccentWashLight, AccentWashDark),
        ("focus-ring", FocusRingLight, FocusRingDark),
        ("wallpaper", WallpaperLight, WallpaperDark),
        ("wallpaper-glow", WallpaperGlowLight, WallpaperGlowDark),
        ("wallpaper-glow-alt", WallpaperGlowAltLight, WallpaperGlowAltDark),
        ("sidebar-ground", SidebarGroundLight, SidebarGroundDark),
        ("glass-clear", GlassClearLight, GlassClearDark),
        ("glass-regular", GlassRegularLight, GlassRegularDark),
        ("glass-thick", GlassThickLight, GlassThickDark),
        ("glass-regular-fallback", GlassRegularFallbackLight, GlassRegularFallbackDark),
        ("glass-thick-fallback", GlassThickFallbackLight, GlassThickFallbackDark),
        ("glass-rim", GlassRimLight, GlassRimDark),
        ("glass-sheen", GlassSheenLight, GlassSheenDark),
        ("glass-edge", GlassEdgeLight, GlassEdgeDark),
        ("glass-hover", GlassHoverLight, GlassHoverDark),
        ("glass-pressed", GlassPressedLight, GlassPressedDark),
        ("inset-fill", InsetFillLight, InsetFillDark),
        ("scrim", ScrimLight, ScrimDark),
        ("divider", DividerLight, DividerDark),
        ("bubble-in", BubbleInLight, BubbleInDark),
        ("bubble-out", BubbleOutLight, BubbleOutDark),
        ("bubble-in-fallback", BubbleInFallbackLight, BubbleInFallbackDark),
        ("bubble-out-fallback", BubbleOutFallbackLight, BubbleOutFallbackDark),
        ("ink", InkLight, InkDark),
        ("ink-secondary", InkSecondaryLight, InkSecondaryDark),
        ("meta-out", MetaOutLight, MetaOutDark),
        ("ink-inverse", InkInverseLight, InkInverseDark),
        ("tick-read", TickReadLight, TickReadDark),
        ("presence-online", PresenceOnlineLight, PresenceOnlineDark),
        ("presence-offline", PresenceOfflineLight, PresenceOfflineDark),
        ("presence-ring", PresenceRingLight, PresenceRingDark),
        ("danger", DangerLight, DangerDark),
        ("danger-ink", DangerInkLight, DangerInkDark),
        ("danger-wash", DangerWashLight, DangerWashDark),
        ("warning", WarningLight, WarningDark),
        ("on-warning", OnWarningLight, OnWarningDark),
        ("warning-ink", WarningInkLight, WarningInkDark),
        ("warning-wash", WarningWashLight, WarningWashDark),
        ("hud-surface", HudSurfaceLight, HudSurfaceDark),
        ("hud-rim", HudRimLight, HudRimDark),
        ("hud-ink", HudInkLight, HudInkDark),
        ("hud-ink-secondary", HudInkSecondaryLight, HudInkSecondaryDark),
        ("hud-button", HudButtonLight, HudButtonDark),
        ("hud-button-hover", HudButtonHoverLight, HudButtonHoverDark),
        ("hud-signal-view", HudSignalViewLight, HudSignalViewDark),
        ("hud-signal-control", HudSignalControlLight, HudSignalControlDark),
        ("avatar-blue", AvatarBlueLight, AvatarBlueDark),
        ("avatar-green", AvatarGreenLight, AvatarGreenDark),
        ("avatar-orange", AvatarOrangeLight, AvatarOrangeDark),
        ("avatar-purple", AvatarPurpleLight, AvatarPurpleDark),
        ("avatar-red", AvatarRedLight, AvatarRedDark),
        ("avatar-teal", AvatarTealLight, AvatarTealDark),
        ("avatar-amber", AvatarAmberLight, AvatarAmberDark),
        ("avatar-slate", AvatarSlateLight, AvatarSlateDark),
    ];

    public static class Radius
    {
        public const double Tail = 4;
        public const double Chip = 6;
        public const double Card = 8;
        public const double Media = 12;
        public const double Bubble = 16;
        public const double Row = 12;
        public const double Panel = 20;
        public const double Sheet = 26;
        public const double Pill = 999;
    }

    public static class Space
    {
        public const double S2 = 2;
        public const double S4 = 4;
        public const double S6 = 6;
        public const double S8 = 8;
        public const double S10 = 10;
        public const double S12 = 12;
        public const double S14 = 14;
        public const double S16 = 16;
        public const double S20 = 20;
        public const double S24 = 24;
    }

    public static class Size
    {
        public const double AvatarRow = 44;
        public const double AvatarHeader = 36;
        public const double Row = 72;
        public const double Header = 56;
        public const double IconButton = 32;
        public const double Send = 36;
        public const double BubbleMax = 420;
        public const double FileBubbleMax = 320;
        public const double MediaMax = 280;
        public const double Presence = 11;
        public const double PresenceInline = 8;
    }

    public static class Acrylic
    {
        public const double ClearTint = 0.3;
        public const double ClearLuminosity = 0.45;
        public const double RegularTint = 0.62;
        public const double RegularLuminosity = 0.8;
        public const double ThickTint = 0.82;
        public const double ThickLuminosity = 0.95;
    }
}
