using LanMessenger.Core.Networking.Media;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LanMessenger.Tests;

/// <summary>
/// The input sub-channel's wire records. Mirror of RemoteInputRecordTests.swift.
///
/// The byte expectations are hand-computed from PROTOCOL.md rather than captured
/// from this implementation. A vector generated by the code it tests only proves
/// the code agrees with itself, and the whole point of these records is that a
/// Mac and a PC agree — the Swift suite asserts the same literals.
/// </summary>
[TestClass]
public class RemoteInputRecordTests
{
    // ---- Wire format -------------------------------------------------------

    [TestMethod]
    public void PointerMoveMatchesTheSpecifiedBytes() =>
        Assert.AreEqual("013e8000003f400000",
            Hex(RemoteInputCodec.Encode(RemoteInputRecord.PointerMove(0.25f, 0.75f))));

    [TestMethod]
    public void PointerButtonMatchesTheSpecifiedBytes() =>
        Assert.AreEqual("0200013f0000003f000000",
            Hex(RemoteInputCodec.Encode(
                RemoteInputRecord.PointerButton(RemotePointerButton.Left, true, 0.5f, 0.5f))));

    [TestMethod]
    public void PointerScrollMatchesTheSpecifiedBytes() =>
        Assert.AreEqual("03bf800000400000003dcccccd3f666666",
            Hex(RemoteInputCodec.Encode(
                RemoteInputRecord.PointerScroll(-1.0f, 2.0f, 0.1f, 0.9f))));

    [TestMethod]
    public void KeyMatchesTheSpecifiedBytes() =>
        Assert.AreEqual("04000401000009",
            Hex(RemoteInputCodec.Encode(RemoteInputRecord.Key(
                0x04, true, false, RemoteInputModifiers.Shift | RemoteInputModifiers.Meta))));

    [TestMethod]
    public void TextMatchesTheSpecifiedBytes() =>
        Assert.AreEqual("0500026869",
            Hex(RemoteInputCodec.Encode(RemoteInputRecord.TextRecord("hi"))));

    [TestMethod]
    public void EveryRecordRoundTrips()
    {
        var records = new List<RemoteInputRecord>
        {
            RemoteInputRecord.PointerMove(0f, 1f),
            RemoteInputRecord.PointerButton(RemotePointerButton.Middle, false, 0.33f, 0.66f),
            RemoteInputRecord.PointerScroll(3f, -4f, 0.5f, 0.5f),
            RemoteInputRecord.Key(0x2C, false, true, RemoteInputModifiers.Control),
            RemoteInputRecord.TextRecord("héllo 👋"),
        };

        foreach (var record in records)
        {
            var decoded = RemoteInputCodec.Decode(RemoteInputCodec.Encode(record));
            Assert.IsNotNull(decoded, $"{record.Kind} did not decode");
            Assert.AreEqual(1, decoded!.Count);
            Assert.AreEqual(record, decoded[0], $"{record.Kind} did not survive a round trip");
        }
    }

    [TestMethod]
    public void SeveralRecordsTravelInOnePayload()
    {
        // A burst of pointer moves must not cost a frame each.
        var burst = new[]
        {
            RemoteInputRecord.PointerMove(0.25f, 0.75f),
            RemoteInputRecord.PointerButton(RemotePointerButton.Left, true, 0.5f, 0.5f),
        };
        byte[] payload = RemoteInputCodec.Encode(burst);
        Assert.AreEqual("013e8000003f4000000200013f0000003f000000", Hex(payload));
        CollectionAssert.AreEqual(burst, RemoteInputCodec.Decode(payload));
    }

    // ---- Hostile input -----------------------------------------------------

    [TestMethod]
    public void ATruncatedRecordIsRejectedRatherThanGuessed()
    {
        // Every byte here came from a peer. A short record means the stream
        // position is no longer trustworthy, and injecting the prefix of a
        // corrupted burst is worse than injecting nothing.
        byte[] full = RemoteInputCodec.Encode(RemoteInputRecord.PointerMove(0.25f, 0.75f));
        for (int cut = 1; cut < full.Length; cut++)
        {
            Assert.IsNull(RemoteInputCodec.Decode(full.AsSpan(0, cut)),
                $"a {cut}-byte pointer_move should not decode");
        }
    }

    [TestMethod]
    public void AnUnknownRecordTypeIsRejected()
    {
        // Not skipped: without a length this build cannot know where the next
        // record starts, so continuing would be guessing.
        Assert.IsNull(RemoteInputCodec.Decode(new byte[] { 0x77, 0x00, 0x00 }));
    }

    [TestMethod]
    public void AReservedButtonIsSkippedButTheStreamContinues()
    {
        // Unlike an unknown type, this record's length IS known — so the stream
        // stays trustworthy and only the one record is dropped.
        var payload = new List<byte> { 0x02, 0x09, 0x01 };            // button 9, reserved
        payload.AddRange(new byte[] { 0x3f, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x00, 0x00 });
        payload.AddRange(RemoteInputCodec.Encode(
            RemoteInputRecord.Key(0x04, true, false, RemoteInputModifiers.None)));

        var decoded = RemoteInputCodec.Decode(payload.ToArray());
        Assert.IsNotNull(decoded);
        Assert.AreEqual(1, decoded!.Count);
        Assert.AreEqual(RemoteInputRecordKind.Key, decoded[0].Kind);
    }

    [TestMethod]
    public void TextLongerThanTheCapIsRefusedOnTheWayIn()
    {
        // The encoder truncates; the decoder refuses. A peer that claims more
        // than the cap is not a peer with a long string, it is a peer trying to
        // make us allocate.
        var data = new List<byte> { 0x05, 0xFF, 0xFF };               // claims 65535 bytes
        data.AddRange(Enumerable.Repeat((byte)0x41, 16));
        Assert.IsNull(RemoteInputCodec.Decode(data.ToArray()));
    }

    [TestMethod]
    public void InvalidUtf8IsAMalformedRecordNotAnEmptyString()
    {
        // Silently injecting nothing would look like a dropped keystroke rather
        // than a broken peer.
        Assert.IsNull(RemoteInputCodec.Decode(new byte[] { 0x05, 0x00, 0x02, 0xC3, 0x28 }));
    }

    [TestMethod]
    public void TextIsTruncatedOnACharacterBoundary()
    {
        // Half a UTF-8 sequence is not a shorter string, it is an invalid one.
        string long_ = string.Concat(Enumerable.Repeat("👋", 600));
        byte[] data = RemoteInputCodec.Encode(RemoteInputRecord.TextRecord(long_));

        var decoded = RemoteInputCodec.Decode(data);
        Assert.IsNotNull(decoded, "a truncated text record should still decode");
        string text = decoded![0].Text!;
        Assert.IsTrue(Encoding.UTF8.GetByteCount(text) <= RemoteInputRecord.MaxTextBytes);
        Assert.AreEqual(0, text.Replace("👋", "").Length, "truncation split a character");
    }

    [TestMethod]
    public void UnknownModifierBitsAreIgnoredRatherThanRejected()
    {
        // A newer peer may set one, and refusing the record would turn a
        // forward-compatible addition into a dead keyboard.
        var decoded = RemoteInputCodec.Decode(
            new byte[] { 0x04, 0x00, 0x04, 0x01, 0x00, 0xFF, 0xFF });
        Assert.IsNotNull(decoded);
        Assert.AreEqual(RemoteInputModifiers.Known, decoded![0].Modifiers);
    }

    // ---- The two gates -----------------------------------------------------

    [TestMethod]
    public void AnEmptyPayloadDecodesToNoRecordsRatherThanFailing()
    {
        // The keepalive is an empty CONTROL frame, but the same reasoning
        // applies here: empty is not malformed. Returning null would make a
        // zero-length burst look like a corrupt peer.
        var decoded = RemoteInputCodec.Decode([]);
        Assert.IsNotNull(decoded);
        Assert.AreEqual(0, decoded!.Count);
    }

    [TestMethod]
    public void AbsoluteCoordinatesSpanTheVirtualDesktopNotTheSharedDisplay()
    {
        // The bug this exists for, found on a two-monitor host. A centre click
        // on a 1920-wide shared display resolves to pixel 960. Scaled against
        // the SURFACE that is 32767/65535 — but MOUSEEVENTF_VIRTUALDESK reads
        // 0..65535 as spanning the whole 3840-wide desktop, so the pointer
        // landed at ~1920px: the left edge of the second monitor. Exactly a
        // factor of two, and completely invisible on one monitor.
        var virtualScreen = new VirtualScreen(0, 0, 3840, 1080);

        var (absX, _) = RemoteInputGeometry.ToAbsolute(960, 540, virtualScreen);
        Assert.IsTrue(absX > 16000 && absX < 16800,
            $"pixel 960 of 3840 should be about a quarter of 65535, got {absX}");

        // And the far edge of the shared display is the MIDDLE of the desktop.
        var (edgeX, _) = RemoteInputGeometry.ToAbsolute(1919, 540, virtualScreen);
        Assert.IsTrue(edgeX > 32000 && edgeX < 33000,
            $"pixel 1919 of 3840 should be about half of 65535, got {edgeX}");
    }

    [TestMethod]
    public void ASecondMonitorSharedFromANonZeroOriginStillResolves()
    {
        // The other half: a shared display need not start at zero. Sharing the
        // right-hand monitor means normalized 0 is virtual pixel 1920, and
        // assuming an origin of zero would put every click on the wrong screen.
        var virtualScreen = new VirtualScreen(0, 0, 3840, 1080);

        var (leftEdge, _) = RemoteInputGeometry.ToAbsolute(1920, 540, virtualScreen);
        var (rightEdge, _) = RemoteInputGeometry.ToAbsolute(3839, 540, virtualScreen);

        Assert.IsTrue(leftEdge > 32000 && leftEdge < 33200, $"got {leftEdge}");
        Assert.AreEqual(65535, rightEdge, "the far edge must reach the top of the range");
    }

    private static string Hex(byte[] data) =>
        string.Concat(data.Select(b => b.ToString("x2")));
}
