#!/usr/bin/env python3
"""Generate the platform token files from design/liquid-glass/tokens.json.

    python3 scripts/design/gen_tokens.py           # write the three files
    python3 scripts/design/gen_tokens.py --check   # exit 1, with a diff, if any is stale

Outputs:
    src/macos/LanMessenger/UI/GlassTokens.swift
    src/windows-native/LanMessenger/UI/GlassTokens.cs
    src/windows-native/LanMessenger/Styles/GlassTokens.xaml

tokens.json is the only place a colour, radius or size is written by hand. A
token change is: edit tokens.json, run this, commit all four files together.
CI runs --check, so a hand edit to a generated file, or a token edit without a
regenerate, fails the build rather than drifting.

Standard library only, deterministic output: running it twice gives no diff.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOKENS = ROOT / "design" / "liquid-glass" / "tokens.json"
SWIFT_OUT = ROOT / "src" / "macos" / "LanMessenger" / "UI" / "GlassTokens.swift"
CS_OUT = ROOT / "src" / "windows-native" / "LanMessenger" / "UI" / "GlassTokens.cs"
XAML_OUT = ROOT / "src" / "windows-native" / "LanMessenger" / "Styles" / "GlassTokens.xaml"

BANNER = "GENERATED by scripts/design/gen_tokens.py from design/liquid-glass/tokens.json. Do not edit."
THEMES = ("light", "dark")


class TokenError(Exception):
    pass


# ── Parsing ──────────────────────────────────────────────────────────────────

_HEX = re.compile(r"^#([0-9a-fA-F]{6})$")
_RGBA = re.compile(r"^rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([0-9.]+)\s*\)$")
_REF = re.compile(r"^\{([a-z0-9-]+)\}$")


def parse_color(text: str) -> int:
    """Returns 0xAARRGGBB for `#rrggbb` or `rgba(r, g, b, a)`."""
    m = _HEX.match(text)
    if m:
        return 0xFF000000 | int(m.group(1), 16)
    m = _RGBA.match(text)
    if m:
        r, g, b = (int(m.group(i)) for i in (1, 2, 3))
        a = float(m.group(4))
        if not all(0 <= c <= 255 for c in (r, g, b)) or not 0 <= a <= 1:
            raise TokenError(f"colour out of range: {text}")
        # round-half-up, so 0.5 × 255 = 127.5 becomes 128 as in CSS, never
        # Python's banker's rounding.
        alpha = int(a * 255 + 0.5)
        return (alpha << 24) | (r << 16) | (g << 8) | b
    raise TokenError(f"unrecognised colour value: {text!r}")


def resolve_colors(tokens: list[dict]) -> dict[str, dict[str, int]]:
    """Resolves every colour token to {theme: argb}, following {name} chains."""
    raw: dict[str, dict[str, str]] = {}
    for token in tokens:
        name = token["name"]
        if name in raw:
            raise TokenError(f"duplicate colour token: {name}")
        value = token["value"]
        if isinstance(value, str):
            raw[name] = {theme: value for theme in THEMES}
        else:
            missing = [t for t in THEMES if t not in value]
            if missing:
                raise TokenError(f"{name}: no value for {', '.join(missing)}")
            raw[name] = {theme: value[theme] for theme in THEMES}

    def resolve(name: str, theme: str, chain: tuple[str, ...]) -> int:
        if name not in raw:
            raise TokenError(f"{' -> '.join(chain)}: no token named {name!r}")
        if name in chain:
            raise TokenError(f"reference cycle: {' -> '.join(chain + (name,))}")
        text = raw[name][theme].strip()
        ref = _REF.match(text)
        if ref:
            return resolve(ref.group(1), theme, chain + (name,))
        return parse_color(text)

    return {name: {theme: resolve(name, theme, ()) for theme in THEMES} for name in raw}


def parse_length(text: str) -> float:
    text = text.strip()
    if text.endswith("px"):
        return float(text[:-2])
    if text.endswith("%"):
        return float(text[:-1]) / 100
    return float(text)


def parse_shadow_layers(text: str) -> list[tuple[float, float, float, int]]:
    """CSS box-shadow → [(x, y, blur, argb)], skipping inset layers."""
    layers = []
    for part in re.split(r",(?![^()]*\))", text):
        part = part.strip()
        if part.startswith("inset"):
            continue
        m = re.match(r"^(-?[0-9.]+)(?:px)?\s+(-?[0-9.]+)(?:px)?\s+([0-9.]+)(?:px)?\s+(rgba\([^)]*\)|#[0-9a-fA-F]{6})$", part)
        if not m:
            raise TokenError(f"unrecognised shadow layer: {part!r}")
        layers.append((float(m.group(1)), float(m.group(2)), float(m.group(3)), parse_color(m.group(4))))
    return layers


# ── Naming ───────────────────────────────────────────────────────────────────

def camel(name: str) -> str:
    head, *rest = name.split("-")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("-"))


def strip_family(name: str, family: str) -> str:
    prefix = family + "-"
    return name[len(prefix):] if name.startswith(prefix) else name


def swift_member(name: str, family: str) -> str:
    """radius-bubble → bubble, space-12 → s12, size-avatar-row → avatarRow."""
    short = strip_family(name, family)
    return "s" + short if short[:1].isdigit() else camel(short)


def cs_member(name: str, family: str) -> str:
    short = strip_family(name, family)
    return "S" + short if short[:1].isdigit() else pascal(short)


def number(value: float) -> str:
    """Shortest exact spelling: 16, 0.75, 1.8."""
    return str(int(value)) if value == int(value) else repr(value)


def argb_hex(argb: int) -> str:
    return f"#{argb:08X}"


# ── Model ────────────────────────────────────────────────────────────────────

class Model:
    def __init__(self, data: dict):
        self.colors = resolve_colors(data["color"]["tokens"])
        self.color_order = [t["name"] for t in data["color"]["tokens"]]
        self.radius = [(t["name"], parse_length(t["value"])) for t in data["radius"]["tokens"]]
        self.space = [(t["name"], parse_length(t["value"])) for t in data["spacing"]["tokens"]]
        self.size = [(t["name"], parse_length(t["value"])) for t in data["size"]["tokens"]]
        self.blur = [(t["name"], parse_length(t["value"])) for t in data["blur"]["tokens"]]
        self.acrylic = {t["name"]: float(t["value"]) for t in data["acrylic"]["tokens"]}
        self.shadows = []
        for t in data["shadow"]["tokens"]:
            value = t["value"]
            per_theme = {theme: parse_shadow_layers(value if isinstance(value, str) else value[theme])
                         for theme in THEMES}
            if any(per_theme.values()):
                self.shadows.append((t["name"], per_theme))
        families = data["type"]["families"]
        self.mono_family = families["mono"]
        self.type_styles = []
        for group in data["type"]["groups"]:
            for style in group["styles"]:
                self.type_styles.append({
                    "name": style["name"],
                    "family": group["family"],
                    "size": parse_length(style["fontSize"]),
                    "line": parse_length(style["lineHeight"]),
                    "weight": int(style["fontWeight"]),
                })
        for needed in ("clear", "regular", "thick"):
            for part in ("tint", "luminosity"):
                if f"acrylic-{needed}-{part}" not in self.acrylic:
                    raise TokenError(f"missing acrylic-{needed}-{part}")


# ── Swift ────────────────────────────────────────────────────────────────────

SWIFT_WEIGHTS = {400: ".regular", 500: ".medium", 600: ".semibold", 700: ".bold"}


def gen_swift(m: Model) -> str:
    out = [f"// {BANNER}", "", "import SwiftUI", "import AppKit", ""]
    out += [
        "/// A colour token's value in each theme, as 0xAARRGGBB.",
        "struct GlassColorPair: Equatable {",
        "    let light: UInt32",
        "    let dark: UInt32",
        "",
        "    /// The value for an explicit scheme, for code that already has one in hand.",
        "    func color(_ scheme: ColorScheme) -> Color {",
        "        Color(argb: scheme == .dark ? dark : light)",
        "    }",
        "}",
        "",
        "/// One non-inset layer of a shadow token. `radius` is SwiftUI's, half the CSS blur.",
        "struct GlassShadowLayer: Equatable {",
        "    let argb: UInt32",
        "    let radius: CGFloat",
        "    let x: CGFloat",
        "    let y: CGFloat",
        "",
        "    var color: Color { Color(argb: argb) }",
        "}",
        "",
        "enum GlassTokens {",
        "    // Dynamic colours: resolve per NSAppearance, so no colorScheme needs threading through.",
    ]
    for name in m.color_order:
        out.append(f"    static let {camel(name)} = Color(glass: Raw.{camel(name)})")
    out += ["", "    /// Every colour token's value in both themes, for tests and explicit-scheme code.", "    enum Raw {"]
    for name in m.color_order:
        v = m.colors[name]
        out.append(f"        static let {camel(name)} = GlassColorPair(light: 0x{v['light']:08X}, dark: 0x{v['dark']:08X})")
    out += ["", "        static let all: [(name: String, value: GlassColorPair)] = ["]
    for name in m.color_order:
        out.append(f'            ("{name}", {camel(name)}),')
    out += ["        ]", "    }", ""]

    def const_enum(title: str, family: str, items: list[tuple[str, float]]) -> list[str]:
        lines = [f"    enum {title} {{"]
        for name, value in items:
            lines.append(f"        static let {swift_member(name, family)}: CGFloat = {number(value)}")
        return lines + ["    }", ""]

    out += const_enum("Radius", "radius", m.radius)
    out += const_enum("Space", "space", m.space)
    out += const_enum("Size", "size", m.size)
    out += const_enum("Blur", "blur", m.blur)

    out.append("    enum Acrylic {")
    for name, value in m.acrylic.items():
        out.append(f"        static let {swift_member(name, 'acrylic')}: Double = {number(value)}")
    out += ["    }", ""]

    out.append("    enum Shadow {")
    for name, per_theme in m.shadows:
        for theme in THEMES:
            member = swift_member(name, "shadow") + theme.capitalize()
            layers = ", ".join(
                f"GlassShadowLayer(argb: 0x{argb:08X}, radius: {number(blur / 2)}, x: {number(x)}, y: {number(y)})"
                for x, y, blur, argb in per_theme[theme])
            out.append(f"        static let {member}: [GlassShadowLayer] = [{layers}]")
    out += ["    }", ""]

    out.append("    enum Typography {")
    for style in m.type_styles:
        weight = SWIFT_WEIGHTS[style["weight"]]
        design = ", design: .monospaced" if style["family"] == "mono" else ""
        out.append(f"        static let {camel(style['name'])} = Font.system(size: {number(style['size'])}, "
                   f"weight: {weight}{design})")
    out += ["    }", "}", ""]

    out += [
        "extension Color {",
        "    /// A colour that follows the view's appearance: light or dark.",
        "    init(glass pair: GlassColorPair) {",
        "        self.init(nsColor: NSColor(name: nil) { appearance in",
        "            let isDark = appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua",
        "            return NSColor(argb: isDark ? pair.dark : pair.light)",
        "        })",
        "    }",
        "",
        "    init(argb: UInt32) {",
        "        self.init(nsColor: NSColor(argb: argb))",
        "    }",
        "}",
        "",
        "extension NSColor {",
        "    fileprivate convenience init(argb: UInt32) {",
        "        self.init(srgbRed: CGFloat((argb >> 16) & 0xFF) / 255,",
        "                  green: CGFloat((argb >> 8) & 0xFF) / 255,",
        "                  blue: CGFloat(argb & 0xFF) / 255,",
        "                  alpha: CGFloat((argb >> 24) & 0xFF) / 255)",
        "    }",
        "}",
    ]
    return "\n".join(out) + "\n"


# ── C# ───────────────────────────────────────────────────────────────────────

def cs_color(argb: int) -> str:
    a, r, g, b = (argb >> 24) & 0xFF, (argb >> 16) & 0xFF, (argb >> 8) & 0xFF, argb & 0xFF
    return f"Color.FromArgb(0x{a:02X}, 0x{r:02X}, 0x{g:02X}, 0x{b:02X})"


def gen_cs(m: Model) -> str:
    out = [f"// {BANNER}", "", "using Windows.UI;", "", "namespace LanMessenger.UI;", ""]
    out += [
        "/// <summary>",
        "/// The design tokens for code-behind. XAML reads the same values from",
        "/// Styles/GlassTokens.xaml as Token*Brush / Token*Color resources.",
        "/// </summary>",
        "public static class GlassTokens",
        "{",
        "    /// <summary>The value for the current theme, as Theme.Initialize last set it.</summary>",
        "    public static Color Pick(Color light, Color dark) => Theme.IsDark ? dark : light;",
        "",
    ]
    for name in m.color_order:
        v = m.colors[name]
        out.append(f"    public static readonly Color {pascal(name)}Light = {cs_color(v['light'])};")
        out.append(f"    public static readonly Color {pascal(name)}Dark = {cs_color(v['dark'])};")
    out += ["", "    /// <summary>Every colour token in both themes, in token order, for tests.</summary>",
            "    public static readonly IReadOnlyList<(string Name, Color Light, Color Dark)> All =", "    ["]
    for name in m.color_order:
        out.append(f'        ("{name}", {pascal(name)}Light, {pascal(name)}Dark),')
    out += ["    ];", ""]

    def const_class(title: str, family: str, items) -> list[str]:
        lines = [f"    public static class {title}", "    {"]
        for name, value in items:
            lines.append(f"        public const double {cs_member(name, family)} = {number(value)};")
        return lines + ["    }", ""]

    out += const_class("Radius", "radius", m.radius)
    out += const_class("Space", "space", m.space)
    out += const_class("Size", "size", m.size)
    out += const_class("Acrylic", "acrylic", list(m.acrylic.items()))
    out[-1:] = ["}"]
    return "\n".join(out) + "\n"


# ── XAML ─────────────────────────────────────────────────────────────────────

# High Contrast maps by role, without acrylic or gradients. First match wins, so
# the specific rules sit above the family-wide ones. A token no rule claims is
# an error: every new token needs a deliberate High Contrast role.
HC_RULES: list[tuple[str, list[str]]] = [
    ("Transparent", ["wallpaper-glow*"]),
    ("SystemColorButtonFaceColor", ["hud-button", "hud-button-hover"]),
    ("SystemColorGrayTextColor", ["presence-offline", "glass-hover", "glass-pressed", "glass-sheen", "avatar-*"]),
    ("SystemColorWindowTextColor", ["ink", "ink-secondary", "meta-out", "glass-edge", "divider", "glass-rim",
                                    "hud-ink", "hud-ink-secondary", "hud-rim"]),
    ("SystemColorHighlightTextColor", ["on-brand", "on-warning", "ink-inverse"]),
    # Washes are fills behind accent content, so they take the window colour:
    # mapping them with their family to Highlight would put Highlight text on a
    # Highlight fill.
    ("SystemColorWindowColor", ["*-wash"]),
    ("SystemColorHighlightColor", ["brand*", "accent-*", "focus-ring", "tick-read", "presence-online",
                                   "warning*", "danger*", "hud-signal-*"]),
    ("SystemColorWindowColor", ["wallpaper", "sidebar-ground", "glass-*", "bubble-*", "*-fallback", "inset-fill",
                                "scrim", "hud-surface", "presence-ring"]),
]


def hc_role(name: str) -> str:
    for role, patterns in HC_RULES:
        for pattern in patterns:
            regex = "^" + re.escape(pattern).replace(r"\*", ".*") + "$"
            if re.match(regex, name):
                return role
    raise TokenError(f"{name}: no High Contrast role (add it to HC_RULES)")


def xaml_color_attr(role: str) -> str:
    return "Transparent" if role == "Transparent" else f"{{ThemeResource {role}}}"


XAML_WEIGHTS = {400: "Normal", 500: "Medium", 600: "SemiBold", 700: "Bold"}

# Colours drawn as a gradient that fades to nothing. Each gets a
# Token<Name>FadeColor: the same RGB at alpha 0, so the gradient fades in its
# own hue instead of through the grey a stop at "Transparent" (#00FFFFFF) drags in.
FADE_TOKENS = ["wallpaper-glow", "wallpaper-glow-alt"]


def gen_xaml(m: Model) -> str:
    def c(name: str, theme: str) -> str:
        return argb_hex(m.colors[name][theme])

    def rgb_opaque(name: str, theme: str) -> str:
        return argb_hex(0xFF000000 | (m.colors[name][theme] & 0xFFFFFF))

    def transparent_twin(name: str, theme: str) -> str:
        return argb_hex(m.colors[name][theme] & 0xFFFFFF)

    out = [
        f"<!-- {BANNER} -->",
        '<ResourceDictionary',
        '    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
        '    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
        "",
        "    <ResourceDictionary.ThemeDictionaries>",
    ]
    for theme, key in (("light", "Light"), ("dark", "Dark")):
        out.append(f'        <ResourceDictionary x:Key="{key}">')
        for name in m.color_order:
            out.append(f'            <Color x:Key="Token{pascal(name)}Color">{c(name, theme)}</Color>')
        for name in FADE_TOKENS:
            out.append(f'            <Color x:Key="Token{pascal(name)}FadeColor">{transparent_twin(name, theme)}</Color>')
        out.append("")
        for name in m.color_order:
            out.append(f'            <SolidColorBrush x:Key="Token{pascal(name)}Brush" Color="{c(name, theme)}" />')
        out.append("")
        for thickness, fallback in (("clear", "glass-regular-fallback"), ("regular", "glass-regular-fallback"),
                                    ("thick", "glass-thick-fallback")):
            out += [
                f'            <AcrylicBrush x:Key="Glass{thickness.capitalize()}AcrylicBrush"',
                f'                          TintColor="{rgb_opaque("glass-" + thickness, theme)}"',
                f'                          TintOpacity="{number(m.acrylic[f"acrylic-{thickness}-tint"])}"',
                f'                          TintLuminosityOpacity="{number(m.acrylic[f"acrylic-{thickness}-luminosity"])}"',
                f'                          FallbackColor="{c(fallback, theme)}" />',
            ]
        out += [
            '            <LinearGradientBrush x:Key="GlassSheenBrush" StartPoint="0,0" EndPoint="0,1">',
            f'                <GradientStop Color="{c("glass-sheen", theme)}" Offset="0" />',
            f'                <GradientStop Color="{transparent_twin("glass-sheen", theme)}" Offset="0.55" />',
            "            </LinearGradientBrush>",
            '            <LinearGradientBrush x:Key="GlassRimBrush" StartPoint="0,0" EndPoint="0,1">',
            f'                <GradientStop Color="{c("glass-rim", theme)}" Offset="0" />',
            f'                <GradientStop Color="{c("glass-edge", theme)}" Offset="0.35" />',
            f'                <GradientStop Color="{c("glass-edge", theme)}" Offset="1" />',
            "            </LinearGradientBrush>",
            "        </ResourceDictionary>",
            "",
        ]

    out.append('        <ResourceDictionary x:Key="HighContrast">')
    for name in m.color_order:
        role = hc_role(name)
        if role == "Transparent":
            out.append(f'            <Color x:Key="Token{pascal(name)}Color">Transparent</Color>')
        else:
            out.append(f'            <StaticResource x:Key="Token{pascal(name)}Color" ResourceKey="{role}" />')
    for name in FADE_TOKENS:
        out.append(f'            <Color x:Key="Token{pascal(name)}FadeColor">Transparent</Color>')
    out.append("")
    for name in m.color_order:
        out.append(f'            <SolidColorBrush x:Key="Token{pascal(name)}Brush" '
                   f'Color="{xaml_color_attr(hc_role(name))}" />')
    out += [
        "",
        '            <SolidColorBrush x:Key="GlassClearAcrylicBrush" Color="{ThemeResource SystemColorWindowColor}" />',
        '            <SolidColorBrush x:Key="GlassRegularAcrylicBrush" Color="{ThemeResource SystemColorWindowColor}" />',
        '            <SolidColorBrush x:Key="GlassThickAcrylicBrush" Color="{ThemeResource SystemColorWindowColor}" />',
        '            <SolidColorBrush x:Key="GlassSheenBrush" Color="Transparent" />',
        '            <SolidColorBrush x:Key="GlassRimBrush" Color="{ThemeResource SystemColorWindowTextColor}" />',
        "        </ResourceDictionary>",
        "    </ResourceDictionary.ThemeDictionaries>",
        "",
    ]

    for title, family, items in (("Radius", "radius", m.radius), ("Space", "space", m.space),
                                 ("Size", "size", m.size)):
        for name, value in items:
            member = cs_member(name, family)
            if family == "radius":
                out.append(f'    <x:Double x:Key="TokenRadius{member}Value">{number(value)}</x:Double>')
                out.append(f'    <CornerRadius x:Key="TokenRadius{member}">{number(value)}</CornerRadius>')
            else:
                out.append(f'    <x:Double x:Key="Token{title}{member}">{number(value)}</x:Double>')
        out.append("")

    out.append(f'    <FontFamily x:Key="TokenMonoFontFamily">Cascadia Mono, Consolas</FontFamily>')
    out.append("")
    for style in m.type_styles:
        out += [
            f'    <Style x:Key="TokenType{pascal(style["name"])}Style" TargetType="TextBlock">',
            f'        <Setter Property="FontSize" Value="{number(style["size"])}" />',
            f'        <Setter Property="LineHeight" Value="{number(style["line"])}" />',
            f'        <Setter Property="FontWeight" Value="{XAML_WEIGHTS[style["weight"]]}" />',
        ]
        if style["family"] == "mono":
            out.append('        <Setter Property="FontFamily" Value="{StaticResource TokenMonoFontFamily}" />')
        out.append("    </Style>")
    out += ["</ResourceDictionary>"]
    return "\n".join(out) + "\n"


# ── Driver ───────────────────────────────────────────────────────────────────

def generate() -> dict[Path, str]:
    model = Model(json.loads(TOKENS.read_text(encoding="utf-8")))
    return {SWIFT_OUT: gen_swift(model), CS_OUT: gen_cs(model), XAML_OUT: gen_xaml(model)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if a generated file differs from disk")
    args = parser.parse_args()

    try:
        outputs = generate()
    except TokenError as error:
        print(f"gen_tokens: {error}", file=sys.stderr)
        return 2

    stale = 0
    for path, text in outputs.items():
        rel = path.relative_to(ROOT).as_posix()
        current = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else ""
        if current == text:
            continue
        if args.check:
            stale += 1
            sys.stdout.writelines(difflib.unified_diff(
                current.splitlines(keepends=True), text.splitlines(keepends=True),
                fromfile=f"{rel} (on disk)", tofile=f"{rel} (from tokens.json)"))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(text)
            print(f"wrote {rel}")

    if stale:
        print(f"\ngen_tokens: {stale} generated file(s) are stale. "
              "Run python3 scripts/design/gen_tokens.py and commit the result.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
