#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parent


def detect_repo_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "main.py").exists() and (candidate / "macos").exists() and (candidate / "windows").exists():
            return candidate
    return ROOT.parent


REPO_ROOT = detect_repo_root(ROOT)
DEFAULT_WINDOWS_INSTALLER = REPO_ROOT / "windows" / "dist-installer" / "LanMessengerSetup.exe"
DEFAULT_MACOS_INSTALLER = REPO_ROOT / "macos" / "releases" / "LAN-Messenger-Installer.dmg"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build the static LAN Messenger update feed.")
    parser.add_argument("--version", required=True, help="Application version to publish, for example 1.4.0")
    parser.add_argument(
        "--windows-installer",
        default=str(DEFAULT_WINDOWS_INSTALLER),
        help="Path to the Windows installer EXE",
    )
    parser.add_argument(
        "--macos-installer",
        default=str(DEFAULT_MACOS_INSTALLER),
        help="Path to the macOS installer DMG",
    )
    parser.add_argument(
        "--notes",
        default="",
        help="Release notes text stored in the manifest and landing page",
    )
    return parser.parse_args()


def ensure_file(path: Path, label: str) -> None:
    if not path.exists() or not path.is_file():
        raise SystemExit(f"{label} not found: {path}")


def copy_installer(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def write_manifest(version: str, notes: str, windows_name: str, macos_name: str) -> None:
    manifest = {
        "version": version,
        "notes": notes,
        "downloads": {
            "windows": f"downloads/{windows_name}",
            "macos": f"downloads/{macos_name}",
        },
    }
    (ROOT / "lan-messenger-update.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def write_index(version: str, notes: str, windows_name: str, macos_name: str) -> None:
    notes_html = f"<p>{notes}</p>" if notes else ""
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>LAN Messenger {version} Updates</title>
  <style>
    :root {{
      --bg: #eef3f8;
      --panel: #ffffff;
      --border: #d6dee8;
      --text: #16202a;
      --muted: #5f6f82;
      --accent: #2f80ed;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: "Segoe UI", sans-serif;
      background: linear-gradient(180deg, #f6fbff 0%, var(--bg) 100%);
      color: var(--text);
    }}
    main {{
      max-width: 760px;
      margin: 0 auto;
      padding: 48px 20px 80px;
    }}
    .card {{
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 24px;
      padding: 28px;
      box-shadow: 0 12px 30px rgba(22, 32, 42, 0.06);
    }}
    .muted {{ color: var(--muted); }}
    .actions {{ display: flex; gap: 12px; flex-wrap: wrap; margin-top: 24px; }}
    .button {{
      display: inline-block;
      padding: 12px 16px;
      border-radius: 12px;
      text-decoration: none;
      font-weight: 600;
      border: 1px solid var(--border);
      color: var(--text);
      background: #f7fafc;
    }}
    .button.primary {{
      background: var(--accent);
      border-color: var(--accent);
      color: #fff;
    }}
    code {{
      background: #f1f5f9;
      padding: 2px 6px;
      border-radius: 6px;
    }}
  </style>
</head>
<body>
  <main>
    <section class="card">
      <h1>LAN Messenger {version}</h1>
      <p class="muted">This page and manifest are generated by <code>build_update_server.py</code>.</p>
      {notes_html}
      <div class="actions">
        <a class="button primary" href="lan-messenger-update.json">Open Manifest</a>
        <a class="button" href="downloads/{windows_name}">Windows Installer</a>
        <a class="button" href="downloads/{macos_name}">macOS Installer</a>
      </div>
    </section>
  </main>
</body>
</html>
"""
    (ROOT / "index.html").write_text(html, encoding="utf-8")


def main() -> None:
    args = parse_args()
    windows_source = Path(args.windows_installer).expanduser().resolve()
    macos_source = Path(args.macos_installer).expanduser().resolve()
    ensure_file(windows_source, "Windows installer")
    ensure_file(macos_source, "macOS installer")

    windows_name = f"LanMessengerSetup-{args.version}.exe"
    macos_name = f"LAN-Messenger-Installer-{args.version}.dmg"

    copy_installer(windows_source, ROOT / "downloads" / windows_name)
    copy_installer(macos_source, ROOT / "downloads" / macos_name)
    write_manifest(args.version, args.notes.strip(), windows_name, macos_name)
    write_index(args.version, args.notes.strip(), windows_name, macos_name)

    print(f"Update feed ready in {ROOT}")
    print(f"Manifest: {ROOT / 'lan-messenger-update.json'}")
    print(f"Windows installer: {ROOT / 'downloads' / windows_name}")
    print(f"macOS installer: {ROOT / 'downloads' / macos_name}")


if __name__ == "__main__":
    main()
