// GENERATED by scripts/design/gen_tokens.py from design/liquid-glass/tokens.json. Do not edit.

import SwiftUI
import AppKit

/// A colour token's value in each theme, as 0xAARRGGBB.
struct GlassColorPair: Equatable {
    let light: UInt32
    let dark: UInt32

    /// The value for an explicit scheme, for code that already has one in hand.
    func color(_ scheme: ColorScheme) -> Color {
        Color(argb: scheme == .dark ? dark : light)
    }
}

/// One non-inset layer of a shadow token. `radius` is SwiftUI's, half the CSS blur.
struct GlassShadowLayer: Equatable {
    let argb: UInt32
    let radius: CGFloat
    let x: CGFloat
    let y: CGFloat

    var color: Color { Color(argb: argb) }
}

enum GlassTokens {
    // Dynamic colours: resolve per NSAppearance, so no colorScheme needs threading through.
    static let brand = Color(glass: Raw.brand)
    static let brandHover = Color(glass: Raw.brandHover)
    static let brandPressed = Color(glass: Raw.brandPressed)
    static let onBrand = Color(glass: Raw.onBrand)
    static let accentInk = Color(glass: Raw.accentInk)
    static let accentInkOut = Color(glass: Raw.accentInkOut)
    static let accentWash = Color(glass: Raw.accentWash)
    static let focusRing = Color(glass: Raw.focusRing)
    static let wallpaper = Color(glass: Raw.wallpaper)
    static let wallpaperGlow = Color(glass: Raw.wallpaperGlow)
    static let wallpaperGlowAlt = Color(glass: Raw.wallpaperGlowAlt)
    static let sidebarGround = Color(glass: Raw.sidebarGround)
    static let glassClear = Color(glass: Raw.glassClear)
    static let glassRegular = Color(glass: Raw.glassRegular)
    static let glassThick = Color(glass: Raw.glassThick)
    static let glassRegularFallback = Color(glass: Raw.glassRegularFallback)
    static let glassThickFallback = Color(glass: Raw.glassThickFallback)
    static let glassRim = Color(glass: Raw.glassRim)
    static let glassSheen = Color(glass: Raw.glassSheen)
    static let glassEdge = Color(glass: Raw.glassEdge)
    static let glassHover = Color(glass: Raw.glassHover)
    static let glassPressed = Color(glass: Raw.glassPressed)
    static let insetFill = Color(glass: Raw.insetFill)
    static let scrim = Color(glass: Raw.scrim)
    static let divider = Color(glass: Raw.divider)
    static let bubbleIn = Color(glass: Raw.bubbleIn)
    static let bubbleOut = Color(glass: Raw.bubbleOut)
    static let bubbleInFallback = Color(glass: Raw.bubbleInFallback)
    static let bubbleOutFallback = Color(glass: Raw.bubbleOutFallback)
    static let ink = Color(glass: Raw.ink)
    static let inkSecondary = Color(glass: Raw.inkSecondary)
    static let metaOut = Color(glass: Raw.metaOut)
    static let inkInverse = Color(glass: Raw.inkInverse)
    static let tickRead = Color(glass: Raw.tickRead)
    static let presenceOnline = Color(glass: Raw.presenceOnline)
    static let presenceOffline = Color(glass: Raw.presenceOffline)
    static let presenceRing = Color(glass: Raw.presenceRing)
    static let danger = Color(glass: Raw.danger)
    static let dangerInk = Color(glass: Raw.dangerInk)
    static let dangerWash = Color(glass: Raw.dangerWash)
    static let warning = Color(glass: Raw.warning)
    static let onWarning = Color(glass: Raw.onWarning)
    static let warningInk = Color(glass: Raw.warningInk)
    static let warningWash = Color(glass: Raw.warningWash)
    static let hudSurface = Color(glass: Raw.hudSurface)
    static let hudRim = Color(glass: Raw.hudRim)
    static let hudInk = Color(glass: Raw.hudInk)
    static let hudInkSecondary = Color(glass: Raw.hudInkSecondary)
    static let hudButton = Color(glass: Raw.hudButton)
    static let hudButtonHover = Color(glass: Raw.hudButtonHover)
    static let hudSignalView = Color(glass: Raw.hudSignalView)
    static let hudSignalControl = Color(glass: Raw.hudSignalControl)
    static let avatarBlue = Color(glass: Raw.avatarBlue)
    static let avatarGreen = Color(glass: Raw.avatarGreen)
    static let avatarOrange = Color(glass: Raw.avatarOrange)
    static let avatarPurple = Color(glass: Raw.avatarPurple)
    static let avatarRed = Color(glass: Raw.avatarRed)
    static let avatarTeal = Color(glass: Raw.avatarTeal)
    static let avatarAmber = Color(glass: Raw.avatarAmber)
    static let avatarSlate = Color(glass: Raw.avatarSlate)

    /// Every colour token's value in both themes, for tests and explicit-scheme code.
    enum Raw {
        static let brand = GlassColorPair(light: 0xFF25D366, dark: 0xFF25D366)
        static let brandHover = GlassColorPair(light: 0xFF1EBE5D, dark: 0xFF1EBE5D)
        static let brandPressed = GlassColorPair(light: 0xFF1AAD54, dark: 0xFF1AAD54)
        static let onBrand = GlassColorPair(light: 0xFF0B141A, dark: 0xFF0B141A)
        static let accentInk = GlassColorPair(light: 0xFF006B57, dark: 0xFF25D366)
        static let accentInkOut = GlassColorPair(light: 0xFF006B57, dark: 0xFF8AF0B5)
        static let accentWash = GlassColorPair(light: 0x2425D366, dark: 0x2925D366)
        static let focusRing = GlassColorPair(light: 0xFF006B57, dark: 0xFF25D366)
        static let wallpaper = GlassColorPair(light: 0xFFE5DDD5, dark: 0xFF0D1418)
        static let wallpaperGlow = GlassColorPair(light: 0x2925D366, dark: 0x2425D366)
        static let wallpaperGlowAlt = GlassColorPair(light: 0x1F008069, dark: 0x1F00A884)
        static let sidebarGround = GlassColorPair(light: 0xFFF0F2F5, dark: 0xFF111B21)
        static let glassClear = GlassColorPair(light: 0x4DFFFFFF, dark: 0x4D111B21)
        static let glassRegular = GlassColorPair(light: 0x9EF8FAFB, dark: 0x9E111B21)
        static let glassThick = GlassColorPair(light: 0xD1FAFBFC, dark: 0xD6161F25)
        static let glassRegularFallback = GlassColorPair(light: 0xFFF0F2F5, dark: 0xFF111B21)
        static let glassThickFallback = GlassColorPair(light: 0xFFFAFBFC, dark: 0xFF161F25)
        static let glassRim = GlassColorPair(light: 0xE6FFFFFF, dark: 0x29FFFFFF)
        static let glassSheen = GlassColorPair(light: 0x73FFFFFF, dark: 0x0FFFFFFF)
        static let glassEdge = GlassColorPair(light: 0x1A0B141A, dark: 0x14FFFFFF)
        static let glassHover = GlassColorPair(light: 0x2E808080, dark: 0x2E808080)
        static let glassPressed = GlassColorPair(light: 0x45808080, dark: 0x45808080)
        static let insetFill = GlassColorPair(light: 0x0D0B141A, dark: 0x12FFFFFF)
        static let scrim = GlassColorPair(light: 0x8C0B141A, dark: 0x8C0B141A)
        static let divider = GlassColorPair(light: 0x140B141A, dark: 0x12FFFFFF)
        static let bubbleIn = GlassColorPair(light: 0xDBFFFFFF, dark: 0xDB202C33)
        static let bubbleOut = GlassColorPair(light: 0xE6DCF8C6, dark: 0xE0005C4B)
        static let bubbleInFallback = GlassColorPair(light: 0xFFFFFFFF, dark: 0xFF202C33)
        static let bubbleOutFallback = GlassColorPair(light: 0xFFDCF8C6, dark: 0xFF005C4B)
        static let ink = GlassColorPair(light: 0xFF111B21, dark: 0xFFE9EDEF)
        static let inkSecondary = GlassColorPair(light: 0xFF54656F, dark: 0xFF8696A0)
        static let metaOut = GlassColorPair(light: 0xFF4F6B52, dark: 0xFFA9D1C6)
        static let inkInverse = GlassColorPair(light: 0xFFFFFFFF, dark: 0xFFFFFFFF)
        static let tickRead = GlassColorPair(light: 0xFF1A7FD4, dark: 0xFF53BDEB)
        static let presenceOnline = GlassColorPair(light: 0xFF1DA05A, dark: 0xFF25D366)
        static let presenceOffline = GlassColorPair(light: 0xFF86868B, dark: 0xFF8E8E93)
        static let presenceRing = GlassColorPair(light: 0xFFFFFFFF, dark: 0xFF111B21)
        static let danger = GlassColorPair(light: 0xFFD93030, dark: 0xFFD93030)
        static let dangerInk = GlassColorPair(light: 0xFFC62828, dark: 0xFFFF7B72)
        static let dangerWash = GlassColorPair(light: 0x24D93030, dark: 0x33D93030)
        static let warning = GlassColorPair(light: 0xFFE68C1A, dark: 0xFFE68C1A)
        static let onWarning = GlassColorPair(light: 0xFF1F1300, dark: 0xFF1F1300)
        static let warningInk = GlassColorPair(light: 0xFF8A5200, dark: 0xFFF5B14C)
        static let warningWash = GlassColorPair(light: 0x24E68C1A, dark: 0x2EE68C1A)
        static let hudSurface = GlassColorPair(light: 0xFF1B1F23, dark: 0xFF1B1F23)
        static let hudRim = GlassColorPair(light: 0x24FFFFFF, dark: 0x24FFFFFF)
        static let hudInk = GlassColorPair(light: 0xFFF2F4F5, dark: 0xFFF2F4F5)
        static let hudInkSecondary = GlassColorPair(light: 0xFFA3ADB4, dark: 0xFFA3ADB4)
        static let hudButton = GlassColorPair(light: 0x1FFFFFFF, dark: 0x1FFFFFFF)
        static let hudButtonHover = GlassColorPair(light: 0x33FFFFFF, dark: 0x33FFFFFF)
        static let hudSignalView = GlassColorPair(light: 0xFFF0A33A, dark: 0xFFF0A33A)
        static let hudSignalControl = GlassColorPair(light: 0xFFFF6159, dark: 0xFFFF6159)
        static let avatarBlue = GlassColorPair(light: 0xFF2B6CD4, dark: 0xFF2B6CD4)
        static let avatarGreen = GlassColorPair(light: 0xFF1B7F45, dark: 0xFF1B7F45)
        static let avatarOrange = GlassColorPair(light: 0xFFB55700, dark: 0xFFB55700)
        static let avatarPurple = GlassColorPair(light: 0xFF8E44C9, dark: 0xFF8E44C9)
        static let avatarRed = GlassColorPair(light: 0xFFD0352B, dark: 0xFFD0352B)
        static let avatarTeal = GlassColorPair(light: 0xFF0B7F99, dark: 0xFF0B7F99)
        static let avatarAmber = GlassColorPair(light: 0xFF9A6500, dark: 0xFF9A6500)
        static let avatarSlate = GlassColorPair(light: 0xFF5E6770, dark: 0xFF5E6770)

        static let all: [(name: String, value: GlassColorPair)] = [
            ("brand", brand),
            ("brand-hover", brandHover),
            ("brand-pressed", brandPressed),
            ("on-brand", onBrand),
            ("accent-ink", accentInk),
            ("accent-ink-out", accentInkOut),
            ("accent-wash", accentWash),
            ("focus-ring", focusRing),
            ("wallpaper", wallpaper),
            ("wallpaper-glow", wallpaperGlow),
            ("wallpaper-glow-alt", wallpaperGlowAlt),
            ("sidebar-ground", sidebarGround),
            ("glass-clear", glassClear),
            ("glass-regular", glassRegular),
            ("glass-thick", glassThick),
            ("glass-regular-fallback", glassRegularFallback),
            ("glass-thick-fallback", glassThickFallback),
            ("glass-rim", glassRim),
            ("glass-sheen", glassSheen),
            ("glass-edge", glassEdge),
            ("glass-hover", glassHover),
            ("glass-pressed", glassPressed),
            ("inset-fill", insetFill),
            ("scrim", scrim),
            ("divider", divider),
            ("bubble-in", bubbleIn),
            ("bubble-out", bubbleOut),
            ("bubble-in-fallback", bubbleInFallback),
            ("bubble-out-fallback", bubbleOutFallback),
            ("ink", ink),
            ("ink-secondary", inkSecondary),
            ("meta-out", metaOut),
            ("ink-inverse", inkInverse),
            ("tick-read", tickRead),
            ("presence-online", presenceOnline),
            ("presence-offline", presenceOffline),
            ("presence-ring", presenceRing),
            ("danger", danger),
            ("danger-ink", dangerInk),
            ("danger-wash", dangerWash),
            ("warning", warning),
            ("on-warning", onWarning),
            ("warning-ink", warningInk),
            ("warning-wash", warningWash),
            ("hud-surface", hudSurface),
            ("hud-rim", hudRim),
            ("hud-ink", hudInk),
            ("hud-ink-secondary", hudInkSecondary),
            ("hud-button", hudButton),
            ("hud-button-hover", hudButtonHover),
            ("hud-signal-view", hudSignalView),
            ("hud-signal-control", hudSignalControl),
            ("avatar-blue", avatarBlue),
            ("avatar-green", avatarGreen),
            ("avatar-orange", avatarOrange),
            ("avatar-purple", avatarPurple),
            ("avatar-red", avatarRed),
            ("avatar-teal", avatarTeal),
            ("avatar-amber", avatarAmber),
            ("avatar-slate", avatarSlate),
        ]
    }

    enum Radius {
        static let tail: CGFloat = 4
        static let chip: CGFloat = 6
        static let card: CGFloat = 8
        static let media: CGFloat = 12
        static let bubble: CGFloat = 16
        static let row: CGFloat = 12
        static let panel: CGFloat = 20
        static let sheet: CGFloat = 26
        static let pill: CGFloat = 999
    }

    enum Space {
        static let s2: CGFloat = 2
        static let s4: CGFloat = 4
        static let s6: CGFloat = 6
        static let s8: CGFloat = 8
        static let s10: CGFloat = 10
        static let s12: CGFloat = 12
        static let s14: CGFloat = 14
        static let s16: CGFloat = 16
        static let s20: CGFloat = 20
        static let s24: CGFloat = 24
    }

    enum Size {
        static let avatarRow: CGFloat = 44
        static let avatarHeader: CGFloat = 36
        static let row: CGFloat = 72
        static let header: CGFloat = 56
        static let iconButton: CGFloat = 32
        static let send: CGFloat = 36
        static let bubbleMax: CGFloat = 420
        static let fileBubbleMax: CGFloat = 320
        static let mediaMax: CGFloat = 280
        static let presence: CGFloat = 11
        static let presenceInline: CGFloat = 8
    }

    enum Blur {
        static let clear: CGFloat = 12
        static let regular: CGFloat = 24
        static let thick: CGFloat = 40
        static let saturateGlass: CGFloat = 1.8
    }

    enum Acrylic {
        static let clearTint: Double = 0.3
        static let clearLuminosity: Double = 0.45
        static let regularTint: Double = 0.62
        static let regularLuminosity: Double = 0.8
        static let thickTint: Double = 0.82
        static let thickLuminosity: Double = 0.95
    }

    enum Shadow {
        static let bubbleLight: [GlassShadowLayer] = [GlassShadowLayer(argb: 0x210B141A, radius: 0.75, x: 0, y: 1)]
        static let bubbleDark: [GlassShadowLayer] = [GlassShadowLayer(argb: 0x4D000000, radius: 0.75, x: 0, y: 1)]
        static let floatLight: [GlassShadowLayer] = [GlassShadowLayer(argb: 0x1F0B141A, radius: 10, x: 0, y: 6), GlassShadowLayer(argb: 0x1A0B141A, radius: 1.5, x: 0, y: 1)]
        static let floatDark: [GlassShadowLayer] = [GlassShadowLayer(argb: 0x73000000, radius: 12, x: 0, y: 8), GlassShadowLayer(argb: 0x66000000, radius: 1.5, x: 0, y: 1)]
        static let sheetLight: [GlassShadowLayer] = [GlassShadowLayer(argb: 0x330B141A, radius: 30, x: 0, y: 24), GlassShadowLayer(argb: 0x1A0B141A, radius: 4, x: 0, y: 2)]
        static let sheetDark: [GlassShadowLayer] = [GlassShadowLayer(argb: 0x99000000, radius: 32, x: 0, y: 24), GlassShadowLayer(argb: 0x80000000, radius: 4, x: 0, y: 2)]
    }

    enum Typography {
        static let titlePane = Font.system(size: 20, weight: .semibold)
        static let titleSheet = Font.system(size: 15, weight: .semibold)
        static let name = Font.system(size: 14, weight: .semibold)
        static let message = Font.system(size: 14, weight: .regular)
        static let preview = Font.system(size: 13, weight: .regular)
        static let fileName = Font.system(size: 13, weight: .medium)
        static let label = Font.system(size: 12, weight: .regular)
        static let labelStrong = Font.system(size: 12, weight: .semibold)
        static let caption = Font.system(size: 11, weight: .regular)
        static let captionStrong = Font.system(size: 11, weight: .semibold)
        static let badge = Font.system(size: 11, weight: .bold)
        static let meta = Font.system(size: 10, weight: .regular)
        static let micro = Font.system(size: 9, weight: .regular)
        static let code = Font.system(size: 12, weight: .regular, design: .monospaced)
    }
}

extension Color {
    /// A colour that follows the view's appearance: light or dark.
    init(glass pair: GlassColorPair) {
        self.init(nsColor: NSColor(name: nil) { appearance in
            let isDark = appearance.bestMatch(from: [.darkAqua, .aqua]) == .darkAqua
            return NSColor(argb: isDark ? pair.dark : pair.light)
        })
    }

    init(argb: UInt32) {
        self.init(nsColor: NSColor(argb: argb))
    }
}

extension NSColor {
    fileprivate convenience init(argb: UInt32) {
        self.init(srgbRed: CGFloat((argb >> 16) & 0xFF) / 255,
                  green: CGFloat((argb >> 8) & 0xFF) / 255,
                  blue: CGFloat(argb & 0xFF) / 255,
                  alpha: CGFloat((argb >> 24) & 0xFF) / 255)
    }
}
